// import "./globals.css";
// import { Navbar, Footer } from "./components";

// export const metadata = {
//   title: "Fitness & Wellness",
//   description: "Generated by create next app",
// };

// export default function RootLayout({ children }: { children: React.ReactNode }) {
//   return (
//     <html lang="en">
//       <body>
//         <main className="max-w-screen-2xl m-auto min-h-screen">
//           <Navbar />
//           {children}
//           <Footer />
//         </main>
//       </body>
//     </html>
//   );
// }

import "./globals.css";
import { Navbar, Footer, ProviderWrapper } from "./components";

export const metadata = {
  title: "Fitness & Wellness",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <main className="max-w-screen-2xl m-auto min-h-screen">
          <ProviderWrapper>
            <Navbar />
            {children}
            <Footer />
          </ProviderWrapper>
        </main>
      </body>
    </html>
  );
}
